# %YAML:1.0

#> 3D Edge Sketch Settings (ABC-NEF)
Num_Of_OMP_Threads: 32                #> Number of CPU cores to run 3D Edge Sketch in parallel
Init_Hypo1_View_Index: 43 #47            #> Initial hypothesis view 1 index
Init_Hypo2_View_Index: 20 #42            #> Initial hypothesis view 2 index
delta: 0.4                            #> edge location perturbation
delta_theta: 15                       #> \Delta \theta: orientation threshold
Max_Num_Of_Support_Views: 8           #> N: minimal number of validation views supporting a hypothesis edge pair
TOED_Thresh: 8                        #> third-order edge detection threshold
Parallel_Epipolar_Line_Angle: 15      #> decide if the picked hypothesis view should be abandoned by the angle between two epipolar lines
Reproj_Dist_Thresh: 2                 #> distance threshold between observed edge and reprojected edge on the validation view (probably not in use)
Ratio_Of_Claimed_Edges_to_Stop: 0.95   #> stopping 3D Edge Sketch by what ratio of "tagged" edges
Max_Num_Of_3D_Edge_Sketch_Passes: 25

#> Dataset Settings
Dataset_Path: /gpfs/data/bkimia/Datasets/
Dataset_Name: ABC-NEF
Scene_Name: 00008231
Total_Num_Of_Images: 50
fx: 1111.11136542426
fy: 1111.11136542426
cx: 399.500000000000
cy: 399.500000000000
Image_Rows: 800
Image_Cols: 800
Use_Multiple_K: false
